### ISSUE TITLE
SteamTest.cs is broken.

### ISSUE THREAD

**Issue by johanneskraem3r** [Facepunch/Facepunch.Steamworks.Unity#2]
Assets/Scripts/SteamTest.cs(89,33): error CS1501: No overload for method `AddScore' takes `9' arguments

leaderBoard.AddScore( true, true, 456, 1, 2, 3, 4, 5, 6 );  

method signature in the dll is : 

public bool AddScore(bool onlyIfBeatsOldScore, int score, params int[] subscores)

**Comment by garrynewman** [comment]
What are you compiling it with?

**Comment by johanneskraem3r** [comment]
Running this in unity.

**Comment by garrynewman** [comment]
What version? Where did you get the dll, did you compile it yourself or get it from releases?

**Comment by johanneskraem3r** [comment]
No, this is literally an unmodified clone of this repo.

**Comment by herpdederp** [comment]
5.6.1f1
Same error as op

**Comment by garrynewman** [comment]
This is all fixed now, sorry it took so long
