### ISSUE TITLE
Doesn't currently work out of the box.

### ISSUE THREAD

**Issue by johanneskraem3r** [Facepunch/Facepunch.Steamworks.Unity#3]
( Hope this is ok to communicate with you like this :) )
When launched, I get the following message: "SteamClient Failed. Make sure appropriate files are in root, and steam is running and signed in."

Should this example "just work" without any modifications? 
Or what are the conditions to get a valid client? 
Which state does the project have to be in on SteamWorks?

**Comment by robotboy655** [comment]
You need the Steam redistributable files in the root folder of your compiled program.

https://github.com/Facepunch/Facepunch.Steamworks.Unity/blob/master/Files%20In%20The%20Project%20Root.txt

These files:
![image](https://user-images.githubusercontent.com/3299036/27755279-6866d34c-5df7-11e7-9747-36579f9bfb84.png)

**Comment by johanneskraem3r** [comment]
Those files are there in the repo ( in the Unity project, right "next to" the `Assets` folder), right? 

So... should this not *just work* if I run it from the Unity Editor? If Steam is running, I should be able to get at least a valid `Client ` , and e.g. log my Steam user name?

Or am I missing something here?

**Comment by robotboy655** [comment]
For the editor I do believe you want it near the Unity.exe. Or try running the built project with the binaries near the built exe.

**Comment by johanneskraem3r** [comment]
Ok, so here's what I was missing: Looks like I need to be logged in with the Steam account linked to the steamworks SDK. I thought it wouldn't matter which one I use. Looks like it does matter.
