### ISSUE TITLE
FindOrCreateLeaderboard

### ISSUE THREAD

**Issue by LoneDev6** [Facepunch/Facepunch.Steamworks.Unity#4]
Is there a way to call FindOrCreateLeaderboard instead of client.GetLeaderboard ?
I'm currently using tesing app id 480, so I can't create leaderboards from the steamworks admin panel.

Thanks

**Comment by garrynewman** [comment]
https://github.com/Facepunch/Facepunch.Steamworks/blob/d944c6c7aebd8b17f1a5927f6ecde1b4f0a5d847/Facepunch.Steamworks/Client.cs#L222

(this is what it calls)

**Comment by LoneDev6** [comment]
Thanks a lot!
