### ISSUE TITLE
Examples Usings Stats or Achievements/ How to increment stats from client?

### ISSUE THREAD

**Issue by jackfranzen** [Facepunch/Facepunch.Steamworks.Unity#5]
Couldn't find any examples which show usage of stats or achievements. 
https://github.com/Facepunch/Facepunch.Steamworks.Unity/blob/master/Assets/Scripts/SteamTest.cs

What's the quickest way to send a stat increment (such as a kill) via the c# client?

**Comment by jackfranzen** [comment]
Found some help searching issues in the other repo here:
https://github.com/Facepunch/Facepunch.Steamworks/issues?utf8=%E2%9C%93&q=stat

**Comment by johanneskraem3r** [comment]
Couldn't find an API function to just inc a value atomically, so this is how I do it currently:

string code = "YOUR_STAT_CODE"; // <== This is the code for the stat that you enter on the Steamworks website.
                int theValue = client.Stats.GetInt(code);
                theValue++;
                client.Stats.Set(code, theValue);
                client.Stats.StoreStats();
