### ISSUE TITLE
Asset store version is missing call to Config.ForUnity()

### ISSUE THREAD

**Issue by PhilippCh** [Facepunch/Facepunch.Steamworks.Unity#6]
Just wanted to let you know that `FacepunchSteamworksTest` in the Unity Asset Store version is currently missing the call to `Facepunch.Steamworks.Config.ForUnity(Application.platform.ToString());`. Scratched my head as to why it was looking for a DLL on OSX for a long time. I don't know which codebase you used to compile the Asset Store package, since the call seems to be present here. Otherwise, I'd be glad to create a PR.

Cheers
Philipp

**Comment by garrynewman** [comment]
Thanks
