### ISSUE TITLE
show example of fetching player avatar

### ISSUE THREAD

**Issue by yamlCase** [Facepunch/Facepunch.Steamworks.Unity#8]
I'm at a loss on the best way to fetch an avatar and display it.  If not too much trouble, could the Unity example project be modified to show this?  Thanks!

**Comment by garrynewman** [comment]
Here you go:

https://garry.tv/2018/01/10/displaying-an-avatar-in-steamworks-unity/

**Comment by yamlCase** [comment]
just what I needed, Thanks Garry!

**Comment by Ornias1993** [comment]
@garrynewman You can close this issue it seems ;)
