### ISSUE TITLE
Best way to do steam-user authentication on a dedicated server (example?)

### ISSUE THREAD

**Issue by Ornias1993** [Facepunch/Facepunch.Steamworks.Unity#9]
@garrynewman your mean repo is a bit vague about it and maybe it works differently with unity anyway... cant find any examples either... So:

How would one go about authenticating steamusers when making a game/project with Unity and Facepunch.Steamworks? Would any of the networking stacks need to be changed too?

**Comment by garrynewman** [comment]
On client get a ticket

```
                var ticket = client.Auth.GetAuthSessionTicket();
                var ticketBinary = ticket.Data;
```

Send the bytes in ticketBinary to the server with their steamid on join.

On server call

```
                    if ( !server.Auth.StartSession( ticketBinary, client.SteamId ) )
                    {
                        Assert.Fail( "Start Session returned false" );
                    }
```

Then you'll get a callback in `server.Auth.OnAuthChange` when the user is authed or rejected.

**Comment by Ornias1993** [comment]
Wow, facepunched/palmed
Thanks Garry, didn't know facepunch.steamworks is literally that easy!
